//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBudget.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDBudgetEntities : DbContext
    {
        public BDBudgetEntities()
            : base("name=BDBudgetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentroGasto> CentroGasto { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<itensOrcamentarios> itensOrcamentarios { get; set; }
        public virtual DbSet<OrcaItem> OrcaItem { get; set; }
        public virtual DbSet<Orcamento> Orcamento { get; set; }
    }
}
