//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoBudget.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcaItem
    {
        public int idorcamento { get; set; }
        public int idItemorcamentario { get; set; }
        public Nullable<int> quantItem { get; set; }
        public string observacao { get; set; }
        public string prioridade { get; set; }

        public double? total { get; set; }

        public double? somaT { get; set; }

        public virtual itensOrcamentarios itensOrcamentarios { get; set; }
        public virtual Orcamento Orcamento { get; set; }
    }
}
